import React, { useState, Children } from "react";
import {
  ChevronRight,
  ChevronDown,
  AlertCircle,
  CheckCircle,
  Info,
  ArrowRight,
  Download,
  Tag,
  X,
  Plus,
} from "lucide-react";
import { motion } from "framer-motion";
import { Badge } from "./Badge";
import { ProgressBar } from "./ProgressBar";
import { Button } from "./Button";
interface SectionProps {
  title: string;
  isOpen?: boolean;
  children: React.ReactNode;
  status?: "success" | "error" | "warning" | "info";
  defaultOpen?: boolean;
}
function Section({
  title,
  defaultOpen = true,
  children,
  status,
}: SectionProps) {
  const [isOpen, setIsOpen] = useState(defaultOpen);
  return (
    <motion.div
      variants={{
        hidden: {
          opacity: 0,
          y: 20,
        },
        visible: {
          opacity: 1,
          y: 0,
        },
      }}
      className="mb-8 border-b border-github-border/40 pb-6 last:border-0 last:pb-0 last:mb-0"
    >
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-center justify-between py-2 group focus:outline-none"
      >
        <div className="flex items-center gap-3">
          <div
            className={`p-1 rounded transition-colors ${
              isOpen
                ? "bg-transparent"
                : "bg-github-btn-bg group-hover:bg-github-btn-hover"
            }`}
          >
            {isOpen ? (
              <ChevronDown size={16} className="text-github-text-secondary" />
            ) : (
              <ChevronRight size={16} className="text-github-text-secondary" />
            )}
          </div>
          <span className="text-sm font-semibold text-github-text-primary group-hover:text-github-text-link transition-colors">
            {title}
          </span>
        </div>
        {status && (
          <Badge
            variant={
              status === "warning"
                ? "warning"
                : status === "error"
                ? "error"
                : "success"
            }
          >
            {status === "error"
              ? "Failed"
              : status === "warning"
              ? "Warning"
              : "Passed"}
          </Badge>
        )}
      </button>

      {isOpen && <div className="mt-4 pl-2">{children}</div>}
    </motion.div>
  );
}
interface ResultsPanelProps {
  onLineClick: (line: number) => void;
  result: any | null;
  error: string | null;
  loading: boolean;
  onAnalyze: () => void;
  onFixFeedback: (fixIndex: number, worked: boolean) => void;
  tags: string[];
  onTagsChange: (tags: string[]) => void;
}
export function ResultsPanel({
  onLineClick,
  result,
  error,
  loading,
  onAnalyze,
  onFixFeedback,
  tags,
  onTagsChange,
}: ResultsPanelProps) {
  const [showExportMenu, setShowExportMenu] = useState(false);
  const [tagInput, setTagInput] = useState("");

  const exportAsMarkdown = () => {
    if (!result) return;

    const timestamp = new Date().toLocaleString();
    const workedFix = result.fixes.findIndex((f) => f.feedback === "worked");

    let markdown = `# FailSense Error Analysis Report\n\n`;
    markdown += `**Generated:** ${timestamp}\n\n`;
    markdown += `---\n\n`;
    markdown += `## 🔴 Error Analysis\n\n`;
    markdown += `**Error Type:** ${result.error_type
      .replace(/_/g, " ")
      .replace(/\b\w/g, (l) => l.toUpperCase())}\n\n`;
    markdown += `**Root Cause:** ${result.root_cause}\n\n`;
    markdown += `**Technical Explanation:**\n${result.explanation}\n\n`;
    markdown += `---\n\n`;
    markdown += `## 💡 Recommended Solutions\n\n`;

    result.fixes.forEach((fix, idx) => {
      markdown += `### Solution #${idx + 1} (${Math.round(
        fix.confidence * 100
      )}% confidence)\n\n`;
      if (workedFix === idx) {
        markdown += `✅ **This solution worked!**\n\n`;
      } else if (fix.feedback === "failed") {
        markdown += `❌ **This solution didn't work**\n\n`;
      }
      markdown += `**Fix:** ${fix.fix}\n\n`;
      markdown += `**Explanation:** ${fix.explanation}\n\n`;
    });

    markdown += `---\n\n`;
    markdown += `*Generated by FailSense - AI-Powered CI/CD Error Debugging*`;

    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `failsense-report-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setShowExportMenu(false);
  };

  const exportAsText = () => {
    if (!result) return;

    const timestamp = new Date().toLocaleString();
    const workedFix = result.fixes.findIndex((f) => f.feedback === "worked");

    let text = `FAILSENSE ERROR ANALYSIS REPORT\n`;
    text += `${"-".repeat(60)}\n\n`;
    text += `Generated: ${timestamp}\n\n`;
    text += `ERROR ANALYSIS\n`;
    text += `${"-".repeat(60)}\n`;
    text += `Error Type: ${result.error_type
      .replace(/_/g, " ")
      .toUpperCase()}\n\n`;
    text += `Root Cause:\n${result.root_cause}\n\n`;
    text += `Technical Explanation:\n${result.explanation}\n\n`;
    text += `${"-".repeat(60)}\n\n`;
    text += `RECOMMENDED SOLUTIONS\n`;
    text += `${"-".repeat(60)}\n\n`;

    result.fixes.forEach((fix, idx) => {
      text += `Solution #${idx + 1} (${Math.round(
        fix.confidence * 100
      )}% confidence)\n`;
      if (workedFix === idx) {
        text += `✓ This solution worked!\n\n`;
      } else if (fix.feedback === "failed") {
        text += `✗ This solution didn't work\n\n`;
      }
      text += `Fix: ${fix.fix}\n\n`;
      text += `Explanation: ${fix.explanation}\n\n`;
      text += `${"-".repeat(40)}\n\n`;
    });

    text += `Generated by FailSense - AI-Powered CI/CD Error Debugging`;

    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `failsense-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setShowExportMenu(false);
  };
  const containerVariants = {
    hidden: {
      opacity: 0,
    },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.15,
        delayChildren: 0.1,
      },
    },
  };
  return (
    <div className="h-full flex flex-col">
      <div className="flex items-center justify-between mb-8 pt-2">
        <h2 className="text-base font-semibold text-github-text-primary">
          Analysis Results
        </h2>
        <div className="flex gap-3">
          {result && (
            <div className="relative">
              <Button
                size="sm"
                variant="secondary"
                onClick={() => setShowExportMenu(!showExportMenu)}
              >
                <span className="flex items-center gap-2">
                  <Download size={14} />
                  Export
                </span>
              </Button>
              {showExportMenu && (
                <div className="absolute right-0 mt-2 w-48 bg-github-surface border border-github-border/60 rounded-lg shadow-xl z-50 overflow-hidden">
                  <button
                    onClick={exportAsMarkdown}
                    className="w-full px-4 py-2.5 text-left text-sm text-github-text-primary hover:bg-github-btn-hover transition-colors flex items-center gap-2"
                  >
                    <Download size={14} />
                    Export as Markdown
                  </button>
                  <button
                    onClick={exportAsText}
                    className="w-full px-4 py-2.5 text-left text-sm text-github-text-primary hover:bg-github-btn-hover transition-colors flex items-center gap-2 border-t border-github-border/30"
                  >
                    <Download size={14} />
                    Export as Text
                  </button>
                </div>
              )}
            </div>
          )}
          <Button
            size="sm"
            variant="primary"
            onClick={onAnalyze}
            isLoading={loading}
          >
            {loading ? "Analyzing..." : "Run Analysis"}
          </Button>
        </div>
      </div>

      {/* Tags Input */}
      <div className="mb-6 p-4 bg-github-surface/40 border border-github-border/40 rounded-lg">
        <label className="block text-xs font-semibold text-github-text-secondary mb-2 uppercase tracking-wider flex items-center gap-2">
          <Tag size={12} />
          Tags (Optional)
        </label>
        <div className="flex flex-wrap gap-2 mb-2">
          {tags.map((tag) => (
            <span
              key={tag}
              className="inline-flex items-center gap-1 px-2.5 py-1 bg-github-info/15 text-github-info border border-github-info/40 rounded-full text-xs"
            >
              {tag}
              <button
                onClick={() => onTagsChange(tags.filter((t) => t !== tag))}
                className="hover:bg-github-info/20 rounded-full p-0.5 transition-colors"
              >
                <X size={12} strokeWidth={2.5} />
              </button>
            </span>
          ))}
        </div>
        <div className="flex gap-2">
          <input
            type="text"
            value={tagInput}
            onChange={(e) => setTagInput(e.target.value)}
            onKeyPress={(e) => {
              if (
                e.key === "Enter" &&
                tagInput.trim() &&
                !tags.includes(tagInput.trim())
              ) {
                onTagsChange([...tags, tagInput.trim()]);
                setTagInput("");
              }
            }}
            placeholder="Add tag (e.g., backend, production, urgent)"
            className="flex-1 px-3 py-1.5 bg-github-bg border border-github-border/40 rounded-md text-sm text-github-text-primary placeholder-github-text-tertiary focus:outline-none focus:border-github-info/50 focus:ring-1 focus:ring-github-info/30 transition-all"
          />
          <button
            onClick={() => {
              if (tagInput.trim() && !tags.includes(tagInput.trim())) {
                onTagsChange([...tags, tagInput.trim()]);
                setTagInput("");
              }
            }}
            disabled={!tagInput.trim() || tags.includes(tagInput.trim())}
            className="px-3 py-1.5 bg-github-btn-bg text-github-text-primary border border-github-border/40 rounded-md text-sm font-medium hover:bg-github-btn-hover disabled:opacity-50 disabled:cursor-not-allowed transition-colors flex items-center gap-1"
          >
            <Plus size={14} />
            Add
          </button>
        </div>
        <p className="text-xs text-github-text-tertiary mt-2">
          Popular: backend, frontend, production, staging, urgent, bug, feature
        </p>
      </div>

      <motion.div
        className="flex-1 overflow-y-auto pr-4 -mr-4 custom-scrollbar"
        variants={containerVariants}
        initial="hidden"
        animate="visible"
      >
        {error && (
          <div className="mb-6 p-4 bg-github-danger/10 border border-github-danger/30 rounded-lg">
            <div className="flex items-start gap-3">
              <AlertCircle size={18} className="text-github-danger mt-0.5" />
              <div>
                <p className="text-sm font-medium text-github-danger mb-1">
                  Analysis Error
                </p>
                <p className="text-sm text-github-text-secondary">{error}</p>
              </div>
            </div>
          </div>
        )}

        {!result && !error && !loading && (
          <div className="flex flex-col items-center justify-center h-full text-center py-12">
            <Info size={48} className="text-github-text-tertiary mb-4" />
            <p className="text-sm text-github-text-secondary mb-2">
              No analysis results yet
            </p>
            <p className="text-xs text-github-text-tertiary">
              Click "Run Analysis" to analyze your code
            </p>
          </div>
        )}

        {result && (
          <>
            {/* Error Analysis Section */}
            <Section title="Error Analysis" status="error">
              <div className="space-y-4">
                <div className="flex items-start gap-5 p-6 bg-gradient-to-br from-github-danger/8 via-github-danger/5 to-transparent rounded-xl border-2 border-github-danger/25 shadow-lg shadow-github-danger/5">
                  <div className="flex-shrink-0 w-14 h-14 rounded-full bg-gradient-to-br from-github-danger/20 to-github-danger/10 border-2 border-github-danger/40 flex items-center justify-center shadow-md">
                    <AlertCircle
                      size={26}
                      className="text-github-danger"
                      strokeWidth={2.5}
                    />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-3 mb-3">
                      <h3 className="text-lg font-bold text-github-text-primary">
                        {result.error_type
                          .replace(/_/g, " ")
                          .replace(/\b\w/g, (l) => l.toUpperCase())}{" "}
                        Error
                      </h3>
                      <span className="px-3 py-1 text-xs font-bold bg-github-danger/15 text-github-danger border-2 border-github-danger/40 rounded-full shadow-sm">
                        Critical
                      </span>
                    </div>
                    <p className="text-base text-github-text-primary mb-5 leading-relaxed font-semibold">
                      {result.root_cause}
                    </p>
                    <div className="p-5 bg-github-surface/80 backdrop-blur-sm rounded-xl border-2 border-github-border/60 shadow-md">
                      <div className="flex items-center gap-2 mb-3">
                        <Info
                          size={16}
                          className="text-github-info"
                          strokeWidth={2.5}
                        />
                        <p className="text-xs text-github-info font-bold uppercase tracking-wider">
                          Technical Explanation
                        </p>
                      </div>
                      <p className="text-sm text-github-text-primary leading-relaxed font-medium">
                        {result.explanation}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </Section>

            {/* Recommended Fixes Section */}
            <Section title="Recommended Fixes" status="warning">
              <div className="space-y-3">
                {result.fixes.map((fix, index) => {
                  const confidenceColor =
                    fix.confidence >= 0.9
                      ? "success"
                      : fix.confidence >= 0.7
                      ? "warning"
                      : "info";

                  return (
                    <motion.div
                      key={index}
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: index * 0.1 }}
                      className="group relative"
                    >
                      <div className="flex items-start gap-4 p-5 bg-gradient-to-br from-github-surface/40 to-github-surface/20 rounded-xl border border-github-border/40 hover:border-github-border/60 transition-all duration-300 hover:shadow-lg hover:shadow-github-info/5">
                        {/* Rank Badge */}
                        <div className="flex-shrink-0 relative">
                          <div
                            className={`w-14 h-14 rounded-full flex items-center justify-center font-bold text-lg transition-all duration-300 ${
                              confidenceColor === "success"
                                ? "bg-gradient-to-br from-github-success/20 to-github-success/10 border-2 border-github-success/40 text-github-success group-hover:scale-110 group-hover:border-github-success/60"
                                : confidenceColor === "warning"
                                ? "bg-gradient-to-br from-github-warning/20 to-github-warning/10 border-2 border-github-warning/40 text-github-warning group-hover:scale-110 group-hover:border-github-warning/60"
                                : "bg-gradient-to-br from-github-info/25 to-github-info/15 border-2 border-github-info/50 text-github-info group-hover:scale-110 group-hover:border-github-info/70"
                            }`}
                          >
                            #{index + 1}
                          </div>
                          {/* Confidence Ring */}
                          <svg
                            className="absolute -inset-1 w-16 h-16"
                            style={{ transform: "rotate(-90deg)" }}
                          >
                            <circle
                              cx="32"
                              cy="32"
                              r="30"
                              fill="none"
                              stroke="currentColor"
                              strokeWidth="2"
                              strokeDasharray={`${
                                fix.confidence * 188.5
                              } 188.5`}
                              className={
                                confidenceColor === "success"
                                  ? "text-github-success/30"
                                  : confidenceColor === "warning"
                                  ? "text-github-warning/30"
                                  : "text-github-info/40"
                              }
                            />
                          </svg>
                        </div>

                        {/* Content */}
                        <div className="flex-1 min-w-0">
                          <div className="flex items-start justify-between gap-3 mb-3">
                            <h4 className="text-base font-semibold text-github-text-primary leading-snug pr-2 group-hover:text-github-text-link transition-colors">
                              {fix.fix}
                            </h4>
                            <span
                              className={`flex-shrink-0 text-xs font-bold px-3 py-1.5 rounded-full shadow-sm ${
                                confidenceColor === "success"
                                  ? "bg-github-success/15 text-github-success border border-github-success/40"
                                  : confidenceColor === "warning"
                                  ? "bg-github-warning/15 text-github-warning border border-github-warning/40"
                                  : "bg-github-info/20 text-github-info border border-github-info/50"
                              }`}
                            >
                              {Math.round(fix.confidence * 100)}%
                            </span>
                          </div>

                          {/* Explanation */}
                          <p className="text-sm text-github-text-secondary leading-relaxed mb-3">
                            {fix.explanation}
                          </p>

                          {/* Progress Bar */}
                          <div className="relative h-1.5 bg-github-border/20 rounded-full overflow-hidden">
                            <motion.div
                              initial={{ width: 0 }}
                              animate={{ width: `${fix.confidence * 100}%` }}
                              transition={{
                                duration: 0.8,
                                delay: index * 0.1 + 0.3,
                              }}
                              className={`h-full rounded-full ${
                                confidenceColor === "success"
                                  ? "bg-gradient-to-r from-github-success/60 to-github-success"
                                  : confidenceColor === "warning"
                                  ? "bg-gradient-to-r from-github-warning/60 to-github-warning"
                                  : "bg-gradient-to-r from-github-info/60 to-github-info"
                              }`}
                            />
                          </div>

                          {/* Feedback Buttons */}
                          <div className="flex items-center gap-2 mt-3 pt-3 border-t border-github-border/20">
                            <span className="text-xs text-github-text-tertiary mr-2">
                              Did this work?
                            </span>
                            <button
                              onClick={() => onFixFeedback(index, true)}
                              className={`flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-md transition-all ${
                                fix.feedback === "worked"
                                  ? "bg-github-success/20 text-github-success border-2 border-github-success/40 shadow-sm"
                                  : "bg-github-surface text-github-text-secondary border border-github-border/40 hover:bg-github-success/10 hover:text-github-success hover:border-github-success/30"
                              }`}
                            >
                              <CheckCircle size={14} strokeWidth={2.5} />
                              Yes
                            </button>
                            <button
                              onClick={() => onFixFeedback(index, false)}
                              className={`flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-md transition-all ${
                                fix.feedback === "failed"
                                  ? "bg-github-danger/20 text-github-danger border-2 border-github-danger/40 shadow-sm"
                                  : "bg-github-surface text-github-text-secondary border border-github-border/40 hover:bg-github-danger/10 hover:text-github-danger hover:border-github-danger/30"
                              }`}
                            >
                              <AlertCircle size={14} strokeWidth={2.5} />
                              No
                            </button>
                          </div>
                        </div>
                      </div>
                    </motion.div>
                  );
                })}
              </div>
            </Section>

            {/* Analysis Summary Footer */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5 }}
              className="mt-6"
            >
              <div className="p-6 bg-gradient-to-r from-github-success/5 via-github-surface/30 to-github-info/5 rounded-xl border border-github-border/50 shadow-lg">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 rounded-full bg-gradient-to-br from-github-success/20 to-github-success/10 border-2 border-github-success/40 flex items-center justify-center">
                      <CheckCircle size={24} className="text-github-success" />
                    </div>
                    <div>
                      <p className="text-base font-semibold text-github-text-primary mb-1">
                        Analysis Complete
                      </p>
                      <p className="text-sm text-github-text-secondary">
                        Found {result.fixes.length}{" "}
                        {result.fixes.length === 1 ? "solution" : "solutions"} •{" "}
                        {result.error_type.replace(/_/g, " ")} error identified
                      </p>
                    </div>
                  </div>
                  <div className="relative">
                    <Button
                      size="sm"
                      variant="secondary"
                      onClick={() => setShowExportMenu(!showExportMenu)}
                    >
                      <span className="flex items-center gap-2">
                        Export Report
                        <ArrowRight size={14} />
                      </span>
                    </Button>
                  </div>
                </div>
              </div>
            </motion.div>
          </>
        )}
      </motion.div>
    </div>
  );
}
